package zotmc.onlysilver.data;

import net.minecraft.item.Item;
import zotmc.onlysilver.util.Dynamic;
import zotmc.onlysilver.util.Dynamic.Construct;
import zotmc.onlysilver.util.Dynamic.Invoke;
import zotmc.onlysilver.util.FluentBoolean;
import cpw.mods.fml.common.ModMetadata;

public class ModData {
	
	public static class OnlySilvers {
		public static final String
		MODID = "onlysilver",
		NAME = "OnlySilver",
		VERSION = "1.9.4-1.7.2",
		DEPENDENCIES = "required-after:Forge@[10.12.2.1121,);after:weaponmod;",
		PACKAGE = "zotmc.onlysilver",
		CLIENT_PROXY = PACKAGE + ".handler.ProxyClient",
		COMMON_PROXY = PACKAGE + ".handler.ProxyCommon";
	}
	
	public static void init(ModMetadata metadata) {
		metadata.autogenerated = false;
		metadata.description = "OnlySilver ports the silver ore and its derivatives from SimpleOres 1.5.2_1"
				+ " to the later versions of Minecraft.";
		metadata.credits = "SimpleOres by AleXndrTheGr8st";
		metadata.authorList.clear();
		metadata.authorList.add("Zot");
	}
	
	
	public static class WeaponMod {
		public static final String
		MODID = "weaponmod", MELEE_COMPONENT = "ckathode.weaponmod.item.MeleeComponent";
		
		public static final FluentBoolean isModLoaded = FluentBoolean.isModLoaded(MODID);
		public static final Invoke<Boolean> isEnabled = Dynamic
				.refer("ckathode.weaponmod.BalkonsWeaponMod", "instance")
				.refer("modConfig")
				.invoke("isEnabled");
		public static final Construct<Item> newItemMelee = Dynamic
				.construct("ckathode.weaponmod.item.ItemMelee");
	}
	
	public static class Thaumcraft {
		public static final String MODID = "Thaumcraft";
	}

}
